# Represents an item's position and characteristics on a map.

# X and Y coordinates defining the item's position.
int16 x # X position of the item
int16 y # Y position of the item

# Size of the item.
uint16 diameter # diameter of the item, in pixels

# Visual characteristic of the item.
string colour # colour of the item

# A numeric value associated with the item, indicating its score.
uint8 value # numerical score associated with the item